unbind r
bind r source-file ~/.tmux.conf

# Set tmux leader key to Ctrl-s
set -g prefix C-s
set -g prefix2 F10
unbind C-b
bind C-s send-prefix

TMUX_FZF_OPTIONS="-p -w 80% -h 70% -m"
set -g mouse on

# act like vim
setw -g mode-keys vi
bind -n C-f copy-mode
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Resize panes with Shift+arrow (no prefix needed)
bind -n S-Left resize-pane -L 4
bind -n S-Right resize-pane -R 4
bind -n S-Up resize-pane -U 4
bind -n S-Down resize-pane -D 4

# Easier and faster switching between next/prev window
# bind-key -n C-S-Left previous-window
# bind-key -n C-S-Right next-window

bind -n M-j previous-window
bind -n M-k next-window
bind -n M-e run-shell -b "~/.tmux/plugins/tmux-fzf/scripts/window.sh switch"

set -g automatic-rename off
set -g status-position top
set -g base-index 1

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'sainnhe/tmux-fzf'
# To launch tmux-fzf, press prefix + F (Shift+F).

set -g @plugin 'ddzero2c/tmux-easymotion#v1.1.0'
set -g @easymotion-s2 'j'
bind-key -T copy-mode-vi Space send-keys -X begin-selection

set -g @plugin 'laktak/extrakto'

set -g @plugin 'niksingh710/minimal-tmux-status' #https://github.com/niksingh710/minimal-tmux-status
set -g @minimal-tmux-status "top"
set -g @minimal-tmux-justify "left"
set -g @minimal-tmux-indicator-str "#S  "
set -g @minimal-tmux-right false
set -g status-left-length 35

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
